### ISSUE TITLE
Edit this page on Github link missing on multiple pages

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#216]
The `Edit this page on Github` link appears only on certain static pages such as 'about' and 'contact'.

**Comment by CyrilBrulebois** [comment]
I've brainstormed on the channel, might be some combination of things like the partial page's got removed (in a97ae5ba31f1ea22466800fb9c6eb941d1e777c9, see `layouts/partials/main/edit-page.html` got emptied) and some pages not getting rebuilt, hence the disparity.

See https://github.com/PiRogueToolSuite/piroguetoolsuite.github.io/blob/v2/layouts/_default/single.html#L64-L66

**Comment by arky** [comment]
I can now see `Edit this page on Github link` on pages so I am going to close this issue as resolved for now.
