### ISSUE TITLE
Multiple Duplicate Entry Warnings 

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#226]
Multiple warnings about duplicate menu entries during build time.

```
| WARN  "piroguetoolsuite.github.io/content/docs/pirogue/architecture/index.md:1:1": duplicate menu entry with identifier "Architecture" in menu "docs"
| WARN  "piroguetoolsuite.github.io/content/docs/pirogue/overview/index.md:1:1": duplicate menu entry with identifier "Overview" in menu "docs"
| WARN  "piroguetoolsuite.github.io/content/docs/pirogue/traffic_analysis/index.md:1:1": duplicate menu entry with identifier "Network traffic analysis" in menu "docs"
| WARN  "piroguetoolsuite.github.io/content/docs/prologue/overview.md:1:1": duplicate menu entry with identifier "Overview" in menu "docs"
```

**Comment by arky** [comment]
Definitely a bug in hugo. Just adding 'identifier' or 'name' doesn't seem to resolve this issue. @U039b perhaps you might have better luck with this?  

https://discourse.gohugo.io/t/duplicate-menu-entry-warning/51231/4

**Comment by U039b** [comment]
Is it really an issue impacting us? I mean, it's just warnings and does not impact the build of the website.

**Comment by arky** [comment]
It might impact in future, the bug relates to how the page title and its corresponding URI is chosen by hugo.
