### ISSUE TITLE
Succinct Project Description on homepage 

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#248]
User feedback suggest breaking down the PTS description on home into concise bullet points for better readability and highlighting key features.

# Before 
> PiRogue tool suite (PTS) provides a platform combining analysis tools, knowledge management, incident response management and artifact management, which allows NGOs with limited resources to equip themselves at a low cost. The project consists of an open-source tool suite that provides a comprehensive mobile device forensics and network traffic analysis platform targeting mobile devices, both for Android and iOS.

# After 
> PiRogue Tool Suite (PTS) is an open-source platform offering cost-effective mobile device forensics and network analysis tools for NGOs.
> * Combines analysis, knowledge management, incident response, and artifact  management.
> * Targets both Android and iOS devices.
> * Empowers NGOs with limited resources.

**Comment by arky** [comment]
@U039b What do you think? Do you have an suggestions to the write up?

**Comment by U039b** [comment]
Instead of explaining all the key features of PTS directly in the description, I suggest we had a section *Features* (and maybe another one *Use cases*) looking like this:

![image](https://github.com/user-attachments/assets/334cb017-98af-4b86-a447-271044927224)

What do you think?

**Comment by arky** [comment]
@U039b I think that is a great idea.  Perhaps it would require complete home page overhaul. Including additional features like  #245

**Comment by arky** [comment]
Superseded by https://github.com/PiRogueToolSuite/piroguetoolsuite.github.io/issues/282
