### ISSUE TITLE
PiRogue Supported Android iOS versions

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#249]
User feedback suggest specifying which operating systems versions are supported by PiRogue section on the homepage.

![image](https://github.com/user-attachments/assets/3eafbfe2-1121-4ed7-90d8-8deb71142c0a)

**Comment by U039b** [comment]
I don't know what to think, the version of Android is relevant for a few features.

**Comment by arky** [comment]
@U039b Let me think on how to clarify this with a single line.
