### ISSUE TITLE
Add more testimonials 

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#250]
User feedback suggests adding more testimonials on PTS project website to build trust and credibility

**Comment by arky** [comment]
@U039b Do you have any additional testimonials? 
I think it we could can show 3 different testimonials as [card grid](https://getdoks.org/docs/basics/shortcodes/#card-grid)

**Comment by U039b** [comment]
We have only one testimonial by now.

**Comment by arky** [comment]
@U039b I have taken the liberty to send a shout out to community if they would like to provide some testimonials. Hope you don't mind

**Comment by arky** [comment]
Superseded by https://github.com/PiRogueToolSuite/piroguetoolsuite.github.io/issues/282
