### ISSUE TITLE
Specify Version numbers in Download links

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#254]
User feedback recommends specifying version number in download page. 

>Perhaps you might want to specify the version of the tool being downloaded rather than simply stating "the latest version." Including the version number will assist the tool operator in determining whether the download will be compatible or not. (if applicable)

![image](https://github.com/user-attachments/assets/38aee632-e7e7-46f3-a419-ccd8bb044f2a)

https://pts-project.org/download/

**Comment by U039b** [comment]
It does not really make sense to add the version on this page. We will add this information if and only if it's a showstopper.

**Comment by arky** [comment]
Let's close this issue as Invaild/Wontfix for now.
