### ISSUE TITLE
Contributors page improvements

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#256]
User feedback suggest adding extra information about project contributors. 

>Providing links for further exploration into the pivotal figures involved in your project aids in comprehension of their roles and facilitates contact with relevant parties.

**Comment by U039b** [comment]
This page does not do the job https://pts-project.org/team/ ?

**Comment by arky** [comment]
@U039b Great! Thanks, I think we can close this issue as resolved.
