### ISSUE TITLE
Add Uncompress Downloaded Image before flashing

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#259]
Add a line about decompressing downloaded image before flashing. Mention that Etcher could handle compressed archives. Perhaps users are unaware of this feature or having flash failures.

> Clarify to decompress archive before flashing SD card with image.
> It would be helpful to have an instruction to first decompress the image and then flash on to the SD card. This instruction should be on the website. "

**Comment by U039b** [comment]
I have no idea why some users are facing issues when flashing the image. AFAIK, Balena Etcher automatically decompress the image before flashing it.

**Comment by CyrilBrulebois** [comment]
Other tools like `gnome-disks` handle that just fine as well.

**Comment by arky** [comment]
Perhaps the reason is that most users are unaware of that you can now flash an uncompressed image with modern tools like gnome-disks and etcher. 

During testing I have indeed noticed that Etcher fails the post-flashing verify step with an error. My guess is that this is noticeable particularly on SD cards with slower write speeds. 

Nevertheless, this issue could be easily fixed with couple of lines in the documentation.
