### ISSUE TITLE
Improve MVT Documentation with references

### ISSUE THREAD

**Issue by arky** [PiRogueToolSuite/piroguetoolsuite.github.io#260]
Expand the `Intermediate guide - How to use MVT to conduct the analysis of a mobile device` guide . Add additional external references, links to other PTS guides.

URL: https://pts-project.org/guides/g7/

> Link out to other, more complete MVT documentation
> MVT guide is helpful but limited, add links to other documentatin or guides

**Comment by U039b** [comment]
I thought the big red warning would be enough 

![image](https://github.com/user-attachments/assets/deb0a170-4b7d-4feb-a291-2b145efef983)

**Comment by arky** [comment]
@U039b In addition to the warning, some additional learning links could be useful for self-exploratory learning. 

![image](https://github.com/user-attachments/assets/86aaa75b-8cce-4f63-a8a3-8f1c7757bfd9)

![image](https://github.com/user-attachments/assets/d7c83a01-f928-4759-8c56-55f0b4a92af4)
